name: Procon-gardener

on:
  schedule:
  - cron: "30 18 * * *"

jobs:
  archive:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install procon-gardener
      run: |
        go install github.com/togatoga/procon-gardener@latest
        procon-gardener init

    - name: Edit config.json
      env:
        ATCODER_ID: ${{ secrets.ATCODER_ID }}
        ATCODER_EMAIL: ${{ secrets.ATCODER_EMAIL }}
      run: |
        cd ../../../.procon-gardener
        jq '.atcoder.repository_path|="."' config.json > tmp
        mv tmp config.json
        jq -r ".atcoder.user_id|=\"$ATCODER_ID\"" config.json > tmp
        mv tmp config.json
        jq -r ".atcoder.user_email|=\"$ATCODER_EMAIL\"" config.json > tmp
        mv tmp config.json

    - name: Archive
      run: procon-gardener archive

    - name: Git push
      run: git push
